# Generated by Django 4.1.3 on 2022-11-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_pie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pies',
        ),
    ]
