# Generated by Django 4.1.3 on 2022-11-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_pies'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='image',
            field=models.ImageField(default='static/website/images/base-pie.png', upload_to=None),
        ),
    ]
