# Generated by Django 4.1.3 on 2022-11-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_pie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='image',
            field=models.ImageField(default='static/website/images/base-pie.png', upload_to='images/'),
        ),
    ]
