# Generated by Django 4.1.3 on 2022-11-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.AlterField(
            model_name='order',
            name='pie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pie'),
        ),
    ]
