# Generated by Django 4.1.3 on 2022-11-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_order_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='image',
            field=models.ImageField(default='images/base-pie.png', upload_to='images/'),
        ),
    ]
